bedtools:
  environment: rnaseq_env_current
bbtools:
  environment: rnaseq_env_current
bcftools:
  environment: rnaseq_env_current
bowtie2:
  environment: rnaseq_env_current
  index: /n/macklis_lab/users/priyav/reference/indexes/bowtie2/plasmid_features/plasmid_features
fastqc:
  environment: rnaseq_env_current
gatk:
  environment: rnaseq_env_current
multiqc:
  environment: rnaseq_env_current
mudskipper:
  index:  /n/macklis_lab/usres/priyav/reference/indexes/mudskipper_GRCm38_101_pPV25_dollar_51
qualimap:
  environment: rnaseq_env_current
salmon:
   environment: rnaseq_env_current
   index: /n/macklis_lab/users/priyav/reference/indexes/salmon/default
samtools:
  environment: rnaseq_env_current
star:
  environment: rnaseq_env_current
  index:   /n/macklis_lab/users/priyav/reference/indexes/star/Mmusculus_GRCm38.101.tdTomato.GFP.readlength100/
rseqc:
  environment: rnaseq_env_current
trimgalore:
  environment: rnaseq_env_current
umi_tools:
  environment: rnaseq_env_current
umi_edist:
  script: /n/home05/pveeraraghavan/lab_notebook/2021.4TU_timecourse/scripts/calculate_UMI_mismatch.py
varscan:
  environment: rnaseq_env_current
  executable: /n/macklis_lab/users/priyav/software/VarScan.v2.3.9.jar
wigtobigwig: /n/macklis_lab/users/priyav/software/wigToBigWig
beds:
  three_prime_utr:  /n/macklis_lab/users/priyav/reference/beds/Mus_musculus.GRCm38.101.pPV25.three_prime_utr.unique.bed
  # generated by sort -i /n/macklis_lab/users/priyav/reference/beds/Mus_musculus.GRCm38.101.pPV25.three_prime_utr.unique.bed | bedtools merge -i - -s -c 4,6 -o distinct | awk -F'\t' 'BEGIN {OFS=FS}{print $1,$2,$3,$4,".",$5}' > /n/macklis_lab/users/priyav/reference/beds/Mus_musculus.GRCm38.101.pPV25.three_prime_utr.unique.merged_named.bed
  three_prime_utr_merged: /n/macklis_lab/users/priyav/reference/beds/Mus_musculus.GRCm38.101.pPV25.three_prime_utr.unique.merged_named.bed # only contains unique genomic intervals
  last250:  /n/macklis_lab/users/priyav/reference/beds/Mmusculus_last_250_bp.bed
  genes_bed12: /n/macklis_lab/users/priyav/reference/beds/Mus_musculus.GRCm38.95.bed12
  exons: /n/macklis_lab/users/priyav/reference/beds/Mus_musculus.GRCm38.101.exons.sorted.bed
indexes:
  bowtie2_rRNA: /n/home05/pveeraraghavan/lab_notebook/reference/index/eukaryote_rRNA
  bowtie2_rodent_repeats: /n/home05/pveeraraghavan/lab_notebook/reference/index/rodent_repeat_elements
fastas:
  polyA_adapters:  /n/macklis_lab/users/priyav/reference/adapters/polyA.fa
  transcriptome: /n/macklis_lab/users/priyav/reference/fastas/Mus_musculus.GRCm38.cdna.from_ens101.tdTomato.GFP.fa  
  genome: /n/macklis_lab/users/priyav/reference/fastas/Mus_musculus.GRCm38.dna.primary_assembly.pPV25_dollar51.fa
  srp: /n/macklis_lab/users/priyav/reference/fastas/contaminants/Rn7s1/ncbi_dataset/data/srp.fna
  rRNA_5s: /n/macklis_lab/users/priyav/reference/fastas/contaminants/rRNA/ensembl_mouse_5s_rRNA.fa
  rRNA_18s: /n/macklis_lab/users/priyav/reference/fastas/contaminants/rRNA/MusMusculus_SSU_rRNA.fa
  rRNA_28s: /n/macklis_lab/users/priyav/reference/fastas/contaminants/rRNA/MusMusculus_LSU_rRNA.fa
  mitochondrial: /n/macklis_lab/users/priyav/reference/fastas/contaminants/mitochondrial/Mus_musculus.GRCm39.dna.chromosome.MT.fa
  repeat_elements: /n/macklis_lab/users/priyav/reference/fastas/contaminants/repeat_elements/rodrepeats.fa
  tRNA: /n/macklis_lab/users/priyav/reference/fastas/contaminants/tRNA/mm10-tRNAs.fa
gtfs: 
  transcriptome: /n/macklis_lab/users/priyav/reference/gtfs/Mus_musculus.GRCm38.101.pPV25.dollar_51.gtf
chrom_sizes: /n/macklis_lab/users/priyav/reference/chrom.sizes.ensembl
workdir: /n/holyscratch01/macklis_lab/priyav/lab_notebook/cpn_cth_paper_final
visualize_dir: /n/macklis_lab/users/priyav/bigWig/cpn_cth_gc_paper_final
lanes:
   - L001
   - L002
mate:
   - R1
   - R2
samples:
   - CPN_Soma1
   - CPN_Soma2
   - CPN_Soma3
   - CPN_Soma4
   - CPN_Soma7
   - CPN_Soma8
   - CPN_Soma9
   - CPN_Soma10
   - CPN_Soma11
   - CPN_Soma12
   - CPN_Soma13
   - CPN_Soma14
   - CTh_Soma1
   - CTh_Soma2
   - CTh_Soma3
   - CTh_Soma5
   - CTh_Soma6
   - CTh_Soma7
   - CTh_Soma8
   - CTh_Soma9
   - CTh_Soma10
