kallisto:
   flags: "-b 100 -t 8 --bias"
   reference: "/n/macklis_lab/users/priyav/reference/indexes/kallisto/mus_musculus/transcriptome.idx"
   modules: "kallisto/0.43.1-fasrc01 hdf5/1.8.12-fasrc08" 
rsem:
   flags: --star -p 12
   reference: "/n/macklis_lab/users/priyav/reference/indexes/rsem/mouse_ensembl_95"
   modules: "centos6/0.0.1-fasrc01 rsem/1.2.29-fasrc02"
trimmomatic:
   flags: -threads 12 -phred33 
   modules: "centos6/0.0.1-fasrc01  ncf/1.0.0-fasrc01"
   path: "/n/home05/pveeraraghavan/lib/Trimmomatic-0.39/trimmomatic-0.39.jar"
workdir: /n/scratchlfs02/macklis_lab/priyav/lab_notebook/2020.1.Hatch_CPN_CTh
run_ids: 
   - 190730_D00742_0312_AH2J5WBCX3  
   - 190805_D00742_0315_BH3L7JBCX3  
   - 191114_D00742_0339_AH7223BCX3
   - 190805_D00742_0314_AH2HYHBCX3  
   - 191018_D00742_0335_AH5NYYBCX3
lanes:
   - L001
   - L002
mate:
   - R1
   - R2
samples:
   - CTh_GC1
   - CTh_GC2
   - CTh_GC3
   - CTh_GC4
   - CTh_GC5
   - CTh_GC6
   - CTh_GC7
   - CTh_GC8
   - CTh_GC9
   - CTh_GC10
   - CTh_GC11
   - CTh_GC12
   - CTh_GC13
   - CTh_GC14
   - CTh_Soma1
   - CTh_Soma2
   - CTh_Soma3
   - CTh_Soma4
   - CTh_Soma5
   - CTh_Soma6
   - CTh_Soma7
   - CTh_Soma8
   - CTh_Soma9
   - CTh_Soma10
   - CTh_Soma11
   - CTh_Soma12
   - CTh_Soma13
   - CTh_Soma14
   - CPN_GC1
   - CPN_GC2
   - CPN_GC3
   - CPN_GC4
   - CPN_GC7
   - CPN_GC8
   - CPN_GC9
   - CPN_GC10
   - CPN_GC11
   - CPN_GC12
   - CPN_GC13
   - CPN_GC14
   - CPN_Soma1
   - CPN_Soma2
   - CPN_Soma3
   - CPN_Soma3
   - CPN_Soma4
   - CPN_Soma5
   - CPN_Soma6
   - CPN_Soma7
   - CPN_Soma8
   - CPN_Soma9
   - CPN_Soma10
   - CPN_Soma11
   - CPN_Soma12
   - CPN_Soma13
   - CPN_Soma14